# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id_university', models.AutoField(primary_key=True, serialize=False)),
                ('name_university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('name_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name_subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('date_tutoring_begin', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Regions')),
                ('tutors_edu', models.ManyToManyField(to='tutoring.Education')),
            ],
        ),
    ]
