# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='tutors_subjects',
            field=models.ManyToManyField(to='tutoring.Subjects'),
        ),
    ]
