# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_tutors_tutors_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutors',
            old_name='tutors_edu',
            new_name='edu',
        ),
        migrations.RenameField(
            model_name='tutors',
            old_name='tutors_subjects',
            new_name='subjects',
        ),
    ]
